### ISSUE TITLE
Launch multiple santas

### ISSUE THREAD

**Issue by darrenvong** [paulienuh/25DaysOfGiphiness#5]
Rather than having this floating around in our chat... let's properly write this down as a feature.

To add to the festive spirit/increased level of silliness, let's have a "secret" santa moving in different directions each time a user clicks on the page.

**Comment by pawlean** [comment]
I WOULD LOVE THIS. 😆

**Comment by BioSok** [comment]
Next week I will write a detailed description for this and implemented in the coming days!

**Comment by darrenvong** [comment]
Ran a quick test last night and I think we might have to limit the number of santas that can be on the page at a time, as a user spam clicking the page can easily crash their browser...

Santas launching/skating across different directions can still be a thing though 🤣
