### ISSUE TITLE
Add a secret santa for one additional GIF opening

### ISSUE THREAD

**Issue by darrenvong** [paulienuh/25DaysOfGiphiness#6]
Currently, only GIFs behind the days that have been elapsed (+ today) can be opened. As an extra feature, we should add a secret santa on the page such that if the user clicks on the page and the secret santa is animated across the page as opposed to a "normal" santa, the user is granted the right to open an additional GIF in ~~a future~~ the following (for simplicity) day.

**Comment by pawlean** [comment]
😂 This would've been epic
