### ISSUE TITLE
Play Christmas music

### ISSUE THREAD

**Issue by darrenvong** [paulienuh/25DaysOfGiphiness#7]
Spun out from #1. Not sure how we'd want to do this, but we could play a Christmas tune/jingle each time someone opens a GIF? Alternatively, each time a Santa is launched, it could play "ho ho ho, Merry Christmas!" or something? 😆

**Comment by pawlean** [comment]
This is a great idea for whenever we decide to work on this project again 😂 Hello from 2021, it sorta sucks but we're doing good. 😂 Closing this.
